---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: installs.home-cloud.io
spec:
  group: home-cloud.io
  names:
    kind: Install
    listKind: InstallList
    plural: installs
    singular: install
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Install is the Schema for the installs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: InstallSpec defines the desired state of Install
            properties:
              gatewayApiSpec:
                properties:
                  version:
                    type: string
                type: object
              homeCloud:
                properties:
                  image:
                    type: string
                  tag:
                    type: string
                type: object
              istio:
                properties:
                  base:
                    properties:
                      values:
                        type: string
                    type: object
                  cni:
                    properties:
                      values:
                        type: string
                    type: object
                  ingressGatewayName:
                    type: string
                  istio:
                    type: string
                  istiod:
                    properties:
                      values:
                        type: string
                    type: object
                  repo:
                    type: string
                  version:
                    type: string
                  ztunnel:
                    properties:
                      values:
                        type: string
                    type: object
                type: object
              settings:
                properties:
                  autoUpdateApps:
                    type: boolean
                  autoUpdateSystem:
                    type: boolean
                  hostname:
                    type: string
                required:
                - autoUpdateApps
                - autoUpdateSystem
                - hostname
                type: object
              talos:
                description: |-
                  optional value to run a system daemon service for managing the host
                  we'll only officially support Talos (for now?) but the community could
                  build others (e.g. NixOS)
                properties:
                  enabled:
                    type: boolean
                  image:
                    type: string
                  tag:
                    type: string
                type: object
              volumeMountHostPath:
                type: string
            type: object
          status:
            description: InstallStatus defines the observed state of Install
            properties:
              daemon:
                properties:
                  enabled:
                    type: boolean
                  image:
                    type: string
                  tag:
                    type: string
                type: object
              istio:
                properties:
                  repo:
                    type: string
                  version:
                    type: string
                type: object
              server:
                properties:
                  image:
                    type: string
                  tag:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
